name: capstone
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - torchvision=0.8.2
  - torchaudio=0.7.2
  - pytorch=1.7.1
  - cudatoolkit
  - numpy=1.18.5
  - pandas=0.25.3
  - scikit-learn=0.22.2
  - Pillow=8.0.1
  - fire
  - scikit-image
  - pip
  - matplotlib
  - jupyterlab
  - pip:
    - tensorflow==2.3.0
    - git+https://github.com/keras-team/keras-tuner.git
    - autokeras
    - medmnist
    - ftfy 
    - regex 
    - tqdm
    - ACSConv
    - git+https://github.com/openai/CLIP.git
